views:
  # Alters the pod view column layout. Uses GVR as key
  v1/pods:
    # Overrides default sort column
    sortColumn: AGE:desc
    columns:
      - "AGE"
      - "NAMESPACE"
      - "NAME"
      - "VS"
      - "READY"
      - "STATUS"
      - "RESTARTS"
      - "NODE"
      - "IP"
      - "PF"
      - "CPU"
      - "MEM"
      - "CPU/R:L"
      - "MEM/R:L"
      - "%CPU/R"
      - "%CPU/L"
      - "%MEM/R"
      - "%MEM/L"
      - "NOMINATED NODE"
      - "READINESS GATES"
      - "QOS"
      - "LABELS"
      - "VALID"

  # Alters the service view column layout
  v1/services:
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - TYPE
      - CLUSTER-IP